version: '3.8'
services:

  # MongoDb Service
  mongodb:
    image: mongo:latest
    container_name: tbs-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./database-data:/data/db

  # Mongo Express Service
  mongo-express:
    image: mongo-express:latest
    container_name: tbs-mongo-express
    restart: unless-stopped
    ports:
      - "8088:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_BASIC_AUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_BASIC_AUTH_PASSWORD}
    depends_on:
      - mongodb

  # Rabbitmq Service
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: tbs-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    networks:
      - tbs-network

  # ZipKin Service
  zipkin:
    image: openzipkin/zipkin
    container_name: tbs-zipkin
    ports:
      - "9411:9411"
    networks:
      - tbs-network

  auth-server:
    image: kjeff42/travel-booking-system-auth-server:0.0.1-SNAPSHOT
    container_name: tbs-auth-server
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      zipkin:
        condition: service_started
      mongodb:
        condition: service_started
    networks:
      - tbs-network

  config-server:
    image: kjeff42/travel-booking-system-config-server:0.0.1-SNAPSHOT
    container_name: tbs-config-server
    ports:
      - "8888:8888"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tbs-network

  discovery-server:
    image: kjeff42/travel-booking-system-discovery-server:0.0.1-SNAPSHOT
    container_name: tbs-discovery-server
    ports:
      - "8761:8761"
    env_file:
      - .env
    depends_on:
      zipkin:
        condition: service_started
      config-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tbs-network

  gateway:
    image: kjeff42/travel-booking-system-gateway:0.0.1-SNAPSHOT
    container_name: tbs-gateway
    ports:
      - "8765:8765"
    env_file:
      - .env
    depends_on:
      zipkin:
        condition: service_started
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    networks:
      - tbs-network

  booking-service:
    image: kjeff42/travel-booking-system-booking-service:0.0.1-SNAPSHOT
    container_name: tbs-booking-service
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_started
      zipkin:
        condition: service_started
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    networks:
      - tbs-network

  category-service:
    image: kjeff42/travel-booking-system-category-service:0.0.1-SNAPSHOT
    container_name: tbs-category-service
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_started
      zipkin:
        condition: service_started
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    networks:
      - tbs-network

  order-service:
    image: kjeff42/travel-booking-system-order-service:0.0.1-SNAPSHOT
    container_name: tbs-order-service
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_started
      zipkin:
        condition: service_started
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    networks:
      - tbs-network

  payment-service:
    image: kjeff42/travel-booking-system-payment-service:0.0.1-SNAPSHOT
    container_name: tbs-payment-service
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_started
      zipkin:
        condition: service_started
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    networks:
      - tbs-network

networks:
  tbs-network:
    driver: bridge
