spring:
  application.name: auth-server
  data.mongodb:
    authentication-database: admin
    username: root
    password: password
    database: user-service
    port: 27017
    host: localhost

  output.ansi.enabled: always

  security:
    oauth2:
      authorizationserver:
        client:
          demo-client:
            #            require-authorization-consent: true
            registration:
              client-id: travel-booking-client
              client-secret: "{noop}secret"
              authorization-grant-types: client_credentials, authorization_code, refresh_token
              redirect-uris: http://127.0.0.1:8765/login/oauth2/code/travel-booking-client
              scopes: user.read, user.write, openid
              client-authentication-methods: client_secret_basic

server:
  port: 8080