spring:
  application.name: auth-server
  data.mongodb:
    authentication-database: ${MONGODB_AUTH_DB}
    username: ${MONGODB_USERNAME}
    password: ${MONGODB_PASSWORD}
    database: ${MONGODB_AUTH_SERVER_DB}
    port: ${MONGODB_PORT}
    host: ${MONGODB_HOST}

  output.ansi.enabled: always

  security:
    oauth2:
      client:
        registration:
          google:
            provider: google
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_SECRET}
            scope: openid, https://www.googleapis.com/auth/userinfo.profile, https://www.googleapis.com/auth/userinfo.email
            client-name: google-client
          github:
            provider: github
            clientId: ${GITHUB_ID}
            clientSecret: ${GITHUB_SECRET}
            scope: user:email, read:user
            client-name: github-client
        provider:
          google.user-name-attribute: email
          github.user-name-attribute: login
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties.mail.smtp:
      auth: true
      starttls.enable: true




server:
  port: 8080
#  address: ${AUTH_SERVER_HOST_NAME}

management.tracing.sampling.probability: 1.0
management.zipkin.tracing.endpoint: ${ZIPKIN_URI}
travel.booking.system:
  frontend-uri: ${FRONTEND_URL}
  gateway-redirect-uri: ${GATEWAY_REDIRECT_URI}
  angular-redirect-uri: ${ANGULAR_REDIRECT_URI}