spring:
  application.name: auth-server
  data.mongodb:
    authentication-database: admin
    username: root
    password: password
    database: user-service
    port: 27017
    host: localhost

  output.ansi.enabled: always

  security:
    oauth2:
      client.registration:
        google:
          client-id: ${google-id}
          client-secret: ${google-secret}
        github:
          clientId: ${github-id}
          clientSecret: ${github-secret}
      authorizationserver:
        client:
          demo-client:
            #            require-authorization-consent: true
            registration:
              client-id: travel-booking-client
              client-secret: "$2a$10$jJtp6plZ0VEDPyE3NkQYJekDRJozhzcllkrQA1g43H2MRiU89xHzm"
              authorization-grant-types: client_credentials, authorization_code, refresh_token
#              redirect-uris: http://127.0.0.1:8765/login/oauth2/code/travel-booking-client
              redirect-uris: https://oauthdebugger.com/debug
              scopes: user.read, user.write, openid
              client-authentication-methods: client_secret_basic
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${email-username}
    password: ${email-app-password}
    properties.mail.smtp:
      auth: true
      starttls.enable: true

jwt-secret: ${jwt-secret}

server:
  port: 8080