spring:
  servlet.multipart:
    max-file-size: 5MB
    max-request-size: 5MB
    enabled: true
  application.name: booking-service
  data.mongodb:
    authentication-database: ${MONGODB_AUTH_DB}
    username: ${MONGODB_USERNAME}
    password: ${MONGODB_PASSWORD}
    database: ${MONGODB_BOOKING_SERVICE_DB}
    port: ${MONGODB_PORT}
    host: ${MONGODB_HOST}
# RabbitMQ config
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWT_SET_URI}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_URI}
  instance:
    hostname: ${BOOKING_SERVICE_HOST_NAME}
    instance-id: ${spring.application.name}:${random.uuid}

# Below property will enable us to access the /actuator/refresh endpoint
management.endpoints.web.exposure.include: "*"
management.tracing.sampling.probability: 1.0

management.zipkin.tracing.endpoint: ${ZIPKIN_URI}
