spring:
  application:
    name: gateway
  # Below property is equivalent to @EnableEurekaClient. It helps API Gateway to register itself to eureka server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes[0]:
        id: booking-service
        uri: lb://booking-service
        predicates[0]: Path=/api/booking-service/**
      routes[1]:
        id: category-service
        uri: lb://category-service
        predicates[0]: Path=/api/category-service/**
      routes[2]:
        id: order-service
        uri: lb://order-service
        predicates[0]: Path=/api/order-service/**
      routes[3]:
        id: payment-service
        uri: lb://payment-service
        predicates[0]: Path=/api/payment-service/**
      # Enable token relay - Pass the successful authenticated token from keycloak server to downstream APIs
      default-filters: TokenRelay
    # Below property tells API Gateway to work in a load balanced mode
    loadbalancer:
      enabled: true

  # Configuration for connecting to spring server
  security:
    oauth2:
      resourceserver:
        jwt:
#          jwk-set-uri: http://localhost:8080/oauth2/jwks
          issuer-uri: ${ISSUER_URI}
      client:
        provider:
          spring:
            issuer-uri: ${ISSUER_URI}
        registration:
          gateway-client:
            provider: spring
            client-id: gateway-client
            client-secret: secret
            authorization-grant-type: authorization_code
#            redirect-uri: http://gateway:8765/login/oauth2/code/gateway-client
            scope:
              - openid
            client-authentication-method: client_secret_basic # The method used for authenticating the client


# Generate a unique name for the instance
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_URI}
  instance:
    hostname: ${GATEWAY_HOST_NAME}
    instance-id: ${spring.application.name}:${random.uuid}

management.tracing.sampling.probability: 1.0
management.zipkin.tracing.endpoint: ${ZIPKIN_URI}
